README.md, extend-expect.d.ts, package.json, src/__tests__/index.js, src/index.js, src/to-have-style.js, src/utils.js
**What**:
A new `.toHaveStyle` custom matcher, as proposed in #6.
Closes #6
**Checklist**:
=> feature: toHaveStyle custom matcher

README.md, src/__tests__/index.js, src/index.js, src/to-be-visible.js
**What**:
A new `.toBeVisible` custom matcher, as discussed in #7 
Closes #7 
**Why**:
Because checking for this manually is not trivial.
**How**:
Using `getComputedStyle` on an element to check if it's not visible either via `display: none` or `visibility: hidden|collapse`. Also checks parent nodes all the way to the top, if any of them is not visible, the element is not visible as well.
**Checklist**:
=> feat: toBeVisible custom matcher

package.json, src/__tests__/__snapshots__/index.js.snap, src/__tests__/index.js, src/to-be-in-the-dom.js, src/to-be-visible.js, src/to-have-attribute.js, src/to-have-class.js, src/to-have-style.js, src/to-have-text-content.js, src/utils.js
**What**:
* It fixes several errors which are thrown with type related messages, e.g. toBeInTheDOM fails with
- str.match is not a function
- Cannot read property 'match' of null
* Also fixes when received value is not html element: error stack was not captured and nice picture of the guilty line was not shown.
* Added snapshots to prevent similar errors in the future
**Why**:
User experience matters for developers too.
**How**:
Mostly by copying ideas from original jest/expect package.
**Checklist**:
=> fix: improved error messages

extend-expect.d.ts
**What**:
Adding toBeVisible to typescript definitions
**Why**:
To help typescript to know about the toBeVisible matcher
**How**:
I added the toBeVisible declaration as part of the interface
**Checklist**:
=> TS - Adding toBeVisible declaration

extend-expect.d.ts
**What**:
A fix for types where it was incorrectly pulling in .src
**Why**:
It will cause errors in Typescript when trying to compile a project with jest-dom
**How**:
Removed the unnecessary reference
**Checklist**:
=> fix: Types incorrectly pulling in .src

README.md, extend-expect.d.ts, src/__tests__/index.js, src/index.js, src/to-have-focus.js
**What**:
Adding ability for user to check to see if the current element has focus
**Why**:
To aid when the user has code that affects which element should be focused at a specific time / event.
**How**:
Checked the element against the document.activeElement.
**Checklist**:
=> feat: add toHaveFocus functionality

README.md, extend-expect.d.ts, src/__tests__/index.js, src/to-have-class.js
**What**:
Allow multiple class name arguments to be provided to `toHaveClass`.
**Why**:
If class names are stored in variables (i.e., if classes are generated at compile or run time), this is a more natural way to assert that multiple classes have been applied. Without this, string concatenation, templating, or multiple assertions would have to be used.
```js
// Before
expect(element).toHaveClass(`${styles.classOne} ${styles.classTwo}`);
// After
expect(element).toHaveClass(styles.classOne, styles.classTwo);
```
~I debated using a variable arguments list rather than an explicit array, but the latter seemed simpler.~
**How**:
~Checked argument type for array.~
Accept variable argument list, split each argument, and flatten results.
**Checklist**:
Open to suggestions on the API or happy to …
=> Accept multiple classname arguments in toHaveClass

README.md
**What**:
Updating readme to have types
**Why**:
To complete #33 
**How**:
Added types (typescript types without return values)
**Checklist**:
Closes #33
=> docs: Updated README to Have Types

README.md, src/__tests__/to-have-class.js, src/to-have-class.js
**What**:
- Require at least one expected class in `toHaveClass` (per https://github.com/gnapse/jest-dom/pull/31#issuecomment-404225469)
- `.not.toHaveClass()` asserts that the actual class list is empty (per https://github.com/gnapse/jest-dom/pull/31#issuecomment-404307031)
**Why**:
- Invoking `toHaveClass` without expected classes will always pass, but is probably indicative of a developer mistake.
- Asserting that a class list is empty (`.not.toHaveClass()`) was not previously possible using this library
**How**:
- Conditional result based on number of expected classes
- `expected.length > 0` &rarr; previous behaviour
- `expected.length === 0` and `isNot` &rarr; assert `received.length === 0`
- `expected.length === 0` and `!isNot` &rarr; fail (at least one class required) …
=> Change toHaveClass behaviour for empty class list

README.md, extend-expect.d.ts, src/__tests__/to-be-in-the-document.js, src/__tests__/to-be-in-the-dom.js, src/__tests__/utils.js, src/index.js, src/to-be-in-the-document.js, src/to-be-in-the-dom.js, src/utils.js
**What**:
Deprecating toBeInTheDOM
Adding toBeInTheDocument
**Why**:
Aiming to implement desires from conversation in issue #34
**How**:
Added a deprecate function to warn of deprecation
Added jsdoc to types to label as deprecated
Added toBeInTheDocument function
Updated documentation to have deprecated notices
Added toBeInTheDocument to documentation
**Checklist**:
@gnapse, @jgoz, and @kentcdodds Here is the first attempt to do the changes we discussed in #34, when you have time please review. :-) !
=> feat: Depreciate toBeInTheDOM with replacement

README.md
**What**:
Fixed a minor error in the README
**Why**:
The error is confusing in the README
**How**:
Changed the svg selector from `html-element` and replaced with `svg-element`
**Checklist**:
=> fix: Updated README to have correct selector

README.md, extend-expect.d.ts, src/__tests__/to-be-in-the-document.js, src/__tests__/to-contain-element.js, src/to-be-in-the-document.js, src/to-contain-element.js
**What**:
- Set toBeInTheDocument and toContainElement to allow null and undefined.
- Adjusted response to make the failing text clearer
**Why**:
On issue #46, expressed the desire to be able to use null in toBeInTheDocument and toContainElement. This is useful when querying for elements that could result in null. It allows code like the following:
```js
// queryByText('Loading...') = null;
expect(queryByText('Loading...')).not.toBeInTheDocument()
expect(container).not.toContainElement(queryByText('Loading...'))
```
Instead of:
```js
expect(queryByText('Loading...').toBeNull();
```
**How**:
- Updated the elements in the matchers to be conditional
- Updated the matching text to make it clearer
- Updated the types to allow null and undefined
**Checklist**:
=> fix: Set toBeInTheDocument and toContainElement to be nullable

src/__tests__/to-have-style.js, src/to-have-style.js, src/utils.js
**What**:
Fixing issue where element styles are formatted differently using `CSSStyleDeclaration` than normal css object.
**Why**:
Causes tests to fail (I.E.: #49), where inconsistencies between `CSSStyleDeclaration`'s and a parsed css object occur.
**How**:
Converted the parsed css text object into CSSStyleDeclaration (using a detached element) before checking.
**Checklist**:
=> fix: #49: update-tohavestyle-to-match-cssstyledeclaration

README.md, extend-expect.d.ts, package.json, src/__tests__/to-have-text-content.js, src/to-have-text-content.js, src/utils.js
**What**:
Implementing #9, it required an adjustment from dom-testing-library as https://github.com/kentcdodds/dom-testing-library/pull/31 makes fuzzy logic optional.
**Why**:
To allow users to test against text with spacing that varies. The text should be normalized to only have one space.
**How**:
As discussed in #9 used [dom-testing-library](https://github.com/kentcdodds/dom-testing-library)'s [get-node-text](https://github.com/kentcdodds/dom-testing-library/blob/master/src/get-node-text.js) function and also included the regex multiple space to one space replacement.
**Checklist**:
=> feat: #9: Normalized whitespace using dom-testing-library

package.json, src/__tests__/to-have-text-content.js, src/to-have-text-content.js, src/utils.js
**What**:
Discussions in #9 showed that `to-have-text-content` lost the ability to go multiple descendant levels. 
**Why**:
Helps fix the issue and allows `to-have-text-content` to handle what it did previously.
**How**:
Removed `dom-testing-library` dependency and replaced with `.textContent` and `normalize utility`.
**Checklist**:
=> fix: #9 adjusted to-have-text-content for multi-level text

package.json, src/to-have-style.js
**What**:
Upgrade dated dependencies.
**Why**:
Mostly to dedupe better on new projects, but it also brings in a bugfix (commented inline)
**How**:
`npx npm-check-updates -u`.
**Checklist**:
=> fix: upgrade jest-diff and jest-matcher-utils

jest.config.js, package.json, src/__tests__/helpers/document.js, src/__tests__/helpers/test-utils.js, src/__tests__/to-be-in-the-document.js, src/__tests__/to-have-style.js, src/__tests__/utils.js, src/to-be-in-the-document.js, src/to-be-visible.js, src/to-contain-html.js, src/to-have-focus.js, src/to-have-style.js, src/utils.js
=> Allow running in node environment

src/to-have-focus.js
**What**:
Added expected to the toHaveFocus matcher
**Why**:
It makes the test results clearer as to what is expected against what is received.
**How**:
Added the expected using `printExpected` with the element
**Checklist**:
=> fix: add expected to matcher toHaveFocus

README.md, extend-expect.d.ts, package.json, src/__tests__/to-have-form-values.js, src/index.js, src/to-have-form-values.js
**What**:
Allow tests to assert that a form (or part of it) contains certain elements with certain corresponding values.
**Why**:
See #60 
**How**:
By gathering all form values under the given container, and matching it against the expected values.
Additional efforts were made to ensure a consistent gathering of form values to match more what a user interprets out of them.
- Handles single vs multiple selection `<select>`
- A set of radio buttons with the same name behave as a single select
- A set of checkboxes with the same name behave as a multi select
- `<input type="number">` is matched as a numeric value, even though internally is a string
- Several elements with the same name are grouped as an array value
**Checklist**:
=> Initial toHaveFormValues implementation (closes #60)

README.md
**What**:
Minor adjustments to the README:
- A typo in a variable name
- A few copy-paste errors in variable names
- Changing the order of a couple of CSS properties to make it clear that the assertion fails because of a different value, not a different order of properties
**Why**:
Just makes the docs easier to read.
**How**:
N/A
**Checklist**:
=> fix: minor typos in README

src/__tests__/utils.js, src/to-contain-html.js, src/utils.js
=> Fix checkHtmlElement helper

.all-contributorsrc, README.md, src/__tests__/to-have-text-content.js, src/utils.js
**What**:
Change `.toHaveTextContent` to be case-sensitive. It closes #71.
**Why**:
This is the expected usage. If the user wants insensitivity, he should do through `Regexp`.
**How**:
Is was removed the `.toLowerCase` from the `match` utils function.
**Checklist**:
=> Fix toHaveTextContent to be case-sensitive

.all-contributorsrc, README.md
**What**:
typo in readme example for `toBeVisible()`
**Why**:
so users can see a correct example
**How**:
text change
**Checklist**:
=> remove extra bracket from toBeVisible example

src/to-contain-html.js
**What**:
#98 prints out html when toContainHTML matcher fails
**Why**:
Before:
After:
**How**:
**Checklist**:
* [] Documentation n/a
* [] Tests n/a
=> fix: display html in toContainHTML failure output #98

.all-contributorsrc, README.md, extend-expect.d.ts, package.json, src/__tests__/to-have-attribute.js, src/to-have-attribute.js
Fixes #91
**Sample Error message**
**What**:
`toHaveAttribute` value will accept `asymmetric` matchers
**Why**:
`asymmetric` matchers are handy when we want to do partial matching
**How**:
Using the method [equals](https://github.com/facebook/jest/blob/ac8c345f5318016d0789974fbc815d857fd70d99/packages/expect/src/jasmineUtils.ts#L30) in `expect/JasmineUtils`
**Checklist**:
=> feat(toHaveAttribute): support asymmetric matchers for value

extend-expect.d.ts
**What/Why**: https://github.com/testing-library/jest-dom/pull/93 introduced a regression into the TypeScript definitions. It used invalid TypeScript syntax and re-declared properties like `not` which conflict with `@types/jest`. Errors for an empty TypeScript project:
```
./node_modules/jest-dom/extend-expect.d.ts:11:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'not' must be of type 'InverseAsymmetricMatchers', but here has type 'InverseStringAsymmetricMatchers'.
11     not: InverseStringAsymmetricMatchers
~~~
./node_modules/jest-dom/extend-expect.d.ts:16:7 - error TS2713: Cannot access 'Expect.stringContaining' because 'Expect' is a type, but not a namespace. Did you mean to retrieve the type of the property 'stringContaining' in 'Expect' with …
```
=> Fix broken type definitions for extend-expect.d.ts

package.json, src/to-have-attribute.js
**What**:
As per the [comment](https://github.com/testing-library/jest-dom/pull/93#discussion_r282040908) by @SimenB
This will remove the direct import of jasmineUtils
`import {equals} from 'expect/build/jasmineUtils'`
and instead use `this.equals`.
Also removes the added dependency of `expect`.
**Why**:
**How**:
**Checklist**:
=> fix: use `this.equals` instead of import jasmineUtils

README.md, extend-expect.d.ts, package.json, src/__tests__/to-be-invalid.js, src/index.js, src/to-be-disabled.js, src/to-be-invalid.js, src/to-be-required.js, src/utils.js
**What**:
This pull-request is a proposed implementation for the custom matchers `toBeInvalid` and `toBeValid`.
**Why**:
This is following a discussion we quickly had with the issue #108.
These two custom matchers can avoid folks to check with different expect tests:
- is having `aria-invalid` not equal to `false`
- `checkValidity` is returning `false`
**How**:
* `toBeInvalid` checks if one of these are correct:
* `aria-invalid` exists and if the value is not equal to `false` (as each value different than false are considered true ([ref](https://www.w3.org/TR/wai-aria-1.1/#aria-invalid)))
* the targetted element is a form element and `checkValidity()` returns `false`
* `toBeValid` checks if all of these are correct:
* `aria-invalid` is not part of the markup or the value is equal to …
=> Implement `toBeInvalid` & `toBeValid` matchers

README.md
**What**:
Fix a typo in __toHaveStyle__ Readme documentation
**Why**:
When we/you try to copy the example from the documentation it is wrong
**How**:
updating the Readme
**Checklist**:
=> Fix a typo in toHaveStyle Readme documentation

.all-contributorsrc, README.md, extend-expect.d.ts, src/__tests__/to-have-value.js, src/index.js, src/to-have-form-values.js, src/to-have-value.js, src/utils.js
**What**:
Add `toHaveValue` matcher
**Why**:
As discussed in #82 
**How**:
Reused a lot of existing logic from `toHaveFormValue` and moved some internal functions  to `utils.js` so that they can be shared between both modules.
I had a lot of thoughts on how to implement this matcher for `<input type="checkbox" />` and `<input type="radio" />`, because those elements value can be different depending on other elements from the same group (sharing the same `name`). Finally I've decided to throw an error when a checkbox or radio input is passed, suggesting users to use `toHaveFormValue` instead. In the future, I think I would most make sense to implement `toBeChecked` matcher - a perfect pair with to `toHaveValue` for single form elements. 
**Checklist**:
=> feat: Add toHaveValue matcher #82

jest.config.js, package.json, src/__tests__/to-be-in-the-document.js, src/__tests__/to-have-value.js, src/__tests__/utils.js, src/to-be-in-the-document.js, tests/jest.config.dom.js, tests/jest.config.node.js, tests/setup-env.js
**What**:
This updates all the packages and gets us to 100% code coverage
**Why**:
Just routine maintenance as I prepare this for #115 
**How**:
`yarn upgrade-interactive --latest` and manually fixing a few things
Note that before there was one jest config, and then the tests were run with `--env jsdom` for running the same tests in both DOM and Node environments. Now we're using projects so we can run all the tests in a single test run.
However this means trouble if you want to scope watch mode down to either node or DOM. So I added `jest-watch-select-projects` which allows you to hit the `P` key during watch mode and toggle on/off each of the projects so you can keep things scoped to the area where you're working.
**Checklist**:
=> chore: update all packages and get 100% coverage

README.md
👋 
**What**:
Update `dom-testing-library` -> `DOM Testing Library` (and same thing with React).
Also point to DTL's guiding principle page instead of Kent's tweet.
**Why**:
Names changed when we moved to scoped packages.
**Checklist**:
=> Update DTL library name + links

.all-contributorsrc, README.md, src/__tests__/to-have-form-values.js, src/utils.js
**What**:
Fixes https://github.com/testing-library/jest-dom/issues/117, adds a test for this use case, and adds me as a contributor.
**Why**:
The `getSelectValue()` util was using `selectedOptions` to get the selected options for a `select`. Because `selectedOptions` is not a reactive property, this was causing a bug where `toHaveFormValues()` would not recognize changed `select` values.
**How**:
This PR updates `getSelectValue()` to use `options` rather than `selectedOptions`, then filter for the selected options, similar to the way this was fixed in [dom-testing-library](https://github.com/testing-library/dom-testing-library/pull/124) (as suggested in the issue).
**Checklist**:
=> fix: recognize changed value of select

README.md, src/__tests__/to-be-invalid.js, src/to-be-invalid.js
**What**:
`toBeValid` and `toBeInvalid` currently support checks against `input` elements by calling `checkValidity()`. <form /> also responds to `checkValidity()`.
**Why**:
Discussed in this issue:
https://github.com/testing-library/jest-dom/issues/125
**How**:
Added `'form'` to the list of tags that can be checked by `toBeValid` and `toBeInvalid`.
**Checklist**:
- [ x] Documentation
=> feat: toBeValid supports <form/> element

src/__tests__/to-have-attribute.js
**What**:
A typo is being corrected.
**Why**:
A typo should not exist in the comments.
**How**:
I fixed the typo and corrected the spelling.
Line 45: Asymettic matchers --> Asymmetric matchers
**Checklist**:
=> chore: typo in to-have-attribute.js comment

src/__tests__/to-have-text-content.js, src/to-have-text-content.js
**What**:
fix #104 
**Why**:
It can cause false-positive tests passing
**How**:
throwing when matching against an empty string, suggesting to use `.toBeEmpty()` instead
**Checklist**:
=> Fix .toHaveTextContent("")  causing false positive

.all-contributorsrc, README.md, src/__tests__/to-have-style.js, src/to-have-style.js, src/utils.js
**What**:
[As the docs says](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style), the `style` property of an HTMLElement should not be directly assigned:
```
Styles should not be set by assigning a string directly to the style property (as in elt.style = "color: blue;"), since it is considered read-only, as the style attribute returns a CSSStyleDeclaration object which is also read-only. Instead, styles can be set by assigning values to the properties of style.
```
This probably is related to the issue: https://github.com/gnapse/jest-dom/issues/68
**Why**:
By directly assigning style, whenever a nonexistent style was passed to `getStyleDeclaration`, it would return an empty object, making `toHaveStyle` always return true in these cases.
**How**:
Since the goal was to …
=> Fix toHaveStyle not to return true when shouldn't

README.md, extend-expect.d.ts, src/__tests__/to-be-checked.js, src/index.js, src/to-be-checked.js, src/to-have-value.js
Closes #107 
**What**:
Added a `toBeChecked` matcher.
**Why**:
It was not implemented in https://github.com/testing-library/jest-dom/pull/90 but I thought it would be a nice addition as there currently isn't a matcher to check the value of a checkbox without it being part of a form.
**How**:
Implemented along the same lines as `toHaveValue` except it's only limited to `<input type="checkbox />`.
I wasn't too sure on the best way to handle `<input type="radio" />` as it can be "checked" and also have a "value", so I've left that for now suggesting to use `toHaveFormValue` instead - similar to how `toHaveValue` handles this situation.
**Checklist**:
=> feat: Add toBeChecked matcher

extend-expect.d.ts
**What**:
`@types/jest` recently had some updates to correct the type for `Matchers`.  This update is a breaking change for any TypeScript project that uses expect.extend.
See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39243
**Why**:
`@testing-library/jest-dom` defines the `Matchers` type in `extend-expect.d.ts`.
**How**:
The change was simply to update the type to match `@types/jest`.
**Checklist**:
=> Update type for Matchers to match @types/jest

src/__tests__/to-have-focus.js
**What**:
Append rendered element to the body in order to allow it to receive focus.
**Why**:
Because of changes in jsdom logic `activeElement` does not return unmounted components. (Fixes #145 )
**How**:
**Checklist**:
=> test: fix focus test

src/__tests__/to-have-style.js, src/to-have-style.js
**What**:
Fixed issue with `.toHaveStyle` not matching `transform: translateX(0px);`.
**Why**:
https://github.com/testing-library/jest-dom/pull/154#discussion_r345172964
**How**:
Discussed in above thread.
**Checklist**:
=> Fixed issue with lowercasing toHaveStyle values.

README.md
Fix README.md for examples under `document.querySelector` to use `document.querySelector` instead of DOM Testing library
**Checklist**:
=> fix: Update examples using document.querySelector

README.md
Close #186 
**What**:
Removing lines in documentation that state you can use `fireEvent.focus(element)`
**Why**:
To avoid confusion. More details & example provided in #186 
**Checklist**:
=> Remove lines about using fireEvent to gain focus or blur

README.md
**What**:
- Removes duplicating examples to show use with both native and @testing-library APIs
- Remove usage of query functions that need to receive the container argument
- Prefer to use `getByTestId` whenever possible
**Why**:
Because why do we need to show the same code twice just to show two different ways to obtain elements from the DOM?
**Checklist**:
=> Simplify README code usage examples

README.md, src/__tests__/to-have-style.js, src/__tests__/utils.js, src/to-have-style.js, src/utils.js
This is a first naive implementation to resolve #179 .
I don't know the best way to generate a css text from an object, so I'm underlying to the DOM to do that.
=> Enhance toHaveStyle to accept JS as css

matchers.js, package.json
Closes #197 
**What**:
Fixes the root `./matchers` module.
**Why**:
#197
=> fix: root matchers module

package.json
**What**:
Moved `pretty-format` to devDependencies since it's not a production dependency, but only a dev dependency.
**Why**:
This will remove an unnecessary dependency from projects that want to use jest-dom. It will also make installation faster and leaner.
**How**:
Checking [Bundlephobia size](https://bundlephobia.com/result?p=@testing-library/jest-dom@5.1.1) and [searching for this package usage](https://github.com/testing-library/jest-dom/search?q=pretty-format&unscoped_q=pretty-format) after noticing that this project added quite a bit of extra weight to my own project.
**Checklist**:
Fixes https://github.com/testing-library/jest-dom/issues/205
=> chore(deps): Move pretty-format to devdependencies

.all-contributorsrc
Otherwise all-contributors PRs can only be merged by people with admin rights.
react-testing-library is running CI as well: https://github.com/testing-library/react-testing-library/blob/c8a869442c94f1bf01b6638b2ce149be3f156bd9/.all-contributorsrc#L10
=> chore: don't skip ci in all-contributors patches

README.md, src/__tests__/to-have-class.js, src/to-have-class.js
Added exact mode option for toHaveClass matcher, as discussed in #176
**How**
```html
<div data-test-id='test-element' class="hello world foo"></div>
```
```javascript
const testElement = getByTestId('test-element')
// toHaveClas is true becose has EXACTLY defined set of classes
expect(testElement).toHaveClass('hello', 'world', 'foo', {exact: true})
// toHaveClas is false because has te set of classes, but it also has 'foo'
expect(testElement).not.toHaveClass('hello', 'world', {exact: true})
// if exact option is not passed or is set as false, it will continue working as before.
expect(testElement).toHaveClass('hello', 'world')
expect(testElement).toHaveClass('hello', 'world', {exact: false})
```
If exact option is not passed or is false, it will continue working as before these changes. …
=> feat: add exact mode option for toHaveClass (#176)

README.md
**What**:
Add a note about `jest-axe` as discussed in https://github.com/testing-library/jest-dom/issues/215.
**Why**:
It may be desirable to further test the validity and accessibility of the DOM beyond what's currently possible with `jest-dom`.
**How**:
Adding a note to the README for others that may have a similar question.
**Checklist**:
=> docs: add note about jest-axe

README.md, src/__tests__/to-be-checked.js, src/to-be-checked.js
**What**:
Add support for the [ARIA switch role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role) to the `toBeChecked` matcher.
**Why**:
The `switch` role works the same as the `checkbox` role, with the switch's status exposed via `aria-checked`, but `toBeChecked()` cannot be used with a switch because only the `checkbox` and `radio` roles are currently implemented.
**How**:
Added `'switch'` to the list of allowed roles in `to-be-checked.js`
**Checklist**:
=> feat: add switch role to toBeChecked

README.md, src/__tests__/to-have-display-value.js, src/matchers.js, src/to-have-display-value.js
**What**:
Add `.toHaveDisplayValue()` custom matcher as discussed here: #221 
**Checklist**:
=> feat: Add `toHaveDisplayValue()` matcher

README.md, src/__tests__/helpers/test-utils.js, src/__tests__/to-have-description.js, src/matchers.js, src/to-have-description.js
**What**:
Adds `toHaveDescription()` matcher
**Why**:
We are able to test labels and accessible names. Almost as popular are descriptions, specified by the `aria-describedby` attribute. It would be great to test these as they often complement labels.
**How**:
- Add `toHaveDescription` matcher with tests
**Checklist**:
I will need help on how to update the type definitions. But I am happy to do so! I know TypeScript well, I’m just not sure how to update the DefinitelyTyped mega repo — do you just pull down the whole thing and make a PR there?
=> Add toHaveDescription()

README.md, src/__tests__/to-have-display-value.js, src/to-have-display-value.js
It closes #239.
All the current specs are kept. I just separate them in contexts to better describe the specs.
This implementation comes with one (good?) side effect: unordered multiple values didn't match before it.
```
<select id="fruits" data-testid="select" multiple>
<option value="">Select a fruit...</option>
<option value="ananas" selected>Ananas</option>
<option value="banana">Banana</option>
<option value="avocado" selected>Avocado</option>
</select>
// This was not true before this PR. It's true now.
expect(subject.queryByTestId('select')).toHaveDisplayValue([
'Avocado',
'Ananas',
])
```
**Checklist**:
=> Allow to use regex on toHaveDisplayValue

.travis.yml
It seems there are still some issues with `npm install` in travis. Old types are still being pulled from somewhere 🤷‍♂️
=> chore(ci): use yarn for install

README.md, src/__tests__/to-be-partially-checked.js, src/matchers.js, src/to-be-partially-checked.js
**What**:
This PR adds a `toBePartiallyChecked` matcher
**Why**:
You can read more about the why in https://github.com/testing-library/jest-dom/issues/243
**How**:
Following the implementation of `toBeChecked` but adapting it to check less elements since `radio` and `switch` cannot have a mixed state.
**Checklist**:
=> feat: add toBePartiallyChecked matcher

README.md, src/__tests__/to-be-empty-dom-element.js, src/matchers.js, src/to-be-empty-dom-element.js, src/to-be-empty.js
**What**:
- Add deprecation note to `toBeEmpty`
- Create `toBeEmptyDomElement` to replace `toBeEmpty`
- Document changes
**Why**:
This is an alternative solution that allows users of `jest-dom` and `jest-extended` to check for emptiness of strings, etc. And DOM elements, using different matchers.
**How**:
- The code of `toBeEmptyDomElement` is a copy of `toBeEmpty`, the only changes in there is the name.
**Checklist**:
- [N/A] Updated Type Definitions
- [?] Ready to be merged
=> feat: Deprecate toBeEmpty in favour of toBeEmptyDOMElement (#216)

package.json
**What**:
Update `@types/testing-library__jest-dom` dependency to the [latest version](https://www.npmjs.com/package/@types/testing-library__jest-dom).
**Why**:
TypeScript doesn't recognize the new `toBeEmptyDOMElement` API from #254 after upgrading the `@testing-library/jest-dom` package in a project (see also the [discussion](https://github.com/testing-library/jest-dom/pull/254#issuecomment-636781036)).
**Checklist**
=> chore: bump @types package version

README.md, src/__tests__/to-be-invalid.js, src/to-be-invalid.js
Closes https://github.com/testing-library/jest-dom/issues/252
**What**:
This PR allows checking if any element is valid, not only on form elements.
**Why**:
Regarding #252 we need to provide a possibility to check the validity of the element even it's not a form element.
**How**:
I adapted `isElementInvalid` function to conditionally call `checkValidity` if element supports it.
**Checklist**:
=> Allow aria-invalid on any element

src/__tests__/to-be-disabled.js, src/to-be-disabled.js
Elements not allowed to be disabled are returning as disabled when inside a disabled fieldset.
```
<fieldset disabled>
// <a /> is enabled even when inside a disabled fieldset
<a />
</fieldset>
```
=> Fix deep element not allowed to be disabled being returned as disabled

package.json, src/__tests__/to-be-checked.js, src/__tests__/to-be-visible.js, src/__tests__/to-have-form-values.js, src/__tests__/to-have-value.js
As discussed in https://github.com/testing-library/jest-dom/pull/196#discussion_r373061623.
=> Disable max-lines-per-function for tests files

package.json, src/__tests__/to-be-checked.js, src/__tests__/utils.js, src/to-be-checked.js, src/utils.js
Instead of hard coding a list of roles, use information provided by the
`aria-query` package to determine whether an element with a given role
supports the `aria-checked` attribute.
Dynamically generate an error message listing all supported roles. Make
error message expectations more fuzzy to prevent test failures if the list
of supported roles should ever change.
Fixes #266
=> Get supported roles for toBeChecked via aria-query

package.json
**What**:
Updating the `css` dependency to the latest version, which no longer depends on `urix`, a deprecated package: https://github.com/lydell/urix
**Why**:
Removes a `yarn`/`npm` warning I've been seeing on install:
```
warning @testing-library/jest-dom > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @testing-library/jest-dom > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```
**How**:
Changed to latest (3.0.0) in `package.json`
**Checklist**:
=> build: update css dependency to latest version

src/__tests__/to-have-style.js, src/__tests__/utils.js, src/to-have-style.js, src/utils.js
**What**:
fixes the issue #272
**Why**:
Current implementation allows false positive matches. More examples in the linked issue 
**Checklist**:
=> fix(toHaveStyle): strictly match empty values

src/__tests__/to-have-text-content.js, src/to-have-text-content.js
**What**:
Suggest using toBeEmptyDOMElement instead of toBeEmpty.
**Why**:
Since PR #254 we are deprecating toBeEmpty in favour of toBeEmptyDOMElement, so we should suggest using it instead.
**How**:
When checking with an empty string using toHaveTextContent, the following error message is displayed:
```
Checking with empty string will always match, use .toBeEmpty() instead
```
In this PR I changed it to:
```
Checking with empty string will always match, use .toBeEmptyDOMElement() instead
```
**Checklist**:
- [ N/A] Documentation
- [ N/A] Updated Type Definitions
=> Suggest using toBeEmptyDOMElement instead of toBeEmpty

README.md
The current toBeInTheDocument examples isn't matching the proposed from @kentcdodds in Common Mistakes - https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-query-variants-for-anything-except-checking-for-non-existence 
Fixing this to help who's starting in the project.
=> doc: match toBeInTheDocument examples with common mistakes

src/__tests__/to-have-style.js, src/to-have-style.js
**What**:
Fixes #280
Fixes #281
**Why**:
As #280, is a regression problem, which wasn't covered by tests.
**How**:
As mentioned by @just-boris, just changed to use the function `getPropertyValue` instead of accessing the property directly.
**Checklist**:
=> Changed toHaveStyle to use getPropertyValue instead of accessing the property directly

README.md
**What**:
Remove duplicate "data-testid" in the readme.
**Why**:
Having two "data-testid" attributes is invalid, so I assume this is a typo/leftover. Removing should simplify example and prevent possible confusion.
**How**:
Self explanatory 😆 
**Checklist**:
=> docs(readme): Remove duplicate "data-testid" from example

README.md
This does not see to be the case anymore, TS works fine since #11
=> Remove TypeScript warning from README

src/__tests__/to-be-in-the-document.js, src/to-be-in-the-document.js
**What**:
`expect(element).toBeInTheDocument()` would return false when `element` was in a shadow root. It now returns true.
**Why**:
I want `toBeInTheDocument` to treat elements in a shadow root as in the document. I am experimenting with using Testing Library on apps that use custom elements.
**How**:
`toBeInTheDocument` originally checked that `element.ownerDocument.contains(element)` was true. However, this returns false if the element being checked is within a shadow root.
I changed the function to use [getRootNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) instead.  `getRootNode` will return the element's root (usually either the document or the element's shadow root). Passing `{composed: true}` will return the document instead of any shadow roots, so we can …
=> fix: treat shadow DOM elements as in the document

README.md
**What**:
Title says it all.
**Why**:
See #144. The motivation comes from how often this was brought up again after that initial issue (see also #230 and #302).
**Checklist**:
N/A
=> docs: Add note about toBeDisabled not supporting aria-disabled

CONTRIBUTING.md, src/to-have-focus.js
**What**:
Added more details to the .toHaveFocus assertion error message
**Why**:
The DOM output when an element is not properly focus does not show any meaningful hints to why an assertion may have failed, which can make errors more difficult to debug 
**How**:
Added additional verbiage to the error message
**Checklist**:
- x] Updated Type Definitions
Open to feedback on the messaging content or verbiage!
=> Improved error messaging for toHaveFocus assertion

jest.config.js
**What**: fixes jest-watch-select-projects so you can type `P` in `npm test` to filter tests in a specific project
**Why**: jest-watch-select-projects was added to the wrong section of the config, causing it to not be enabled
**How**: moved the package from projects to watch plugins
**Checklist**:
=> chore: fix jest-watch-select-projects

src/__tests__/to-have-display-value.js, src/to-have-display-value.js
**What**: Uses an equality check on strings passed to `toHaveDisplayValue`
**Why**: #290
**How**: Use `this.equals` (equality check) instead of `matches` (which uses `includes` for substrings)
**Checklist**:
=> fix: check equality in toHaveDisplayValue (fix #290)

src/__tests__/to-contain-html.js, src/to-contain-html.js
**What**:
No expected message when tests fail when `toContainHTML` matcher is used
**Why**:
Fixes #299 
**How**:
Added an expected block with `htmlText` as the expected string with 'Expected' colour using `utils.EXPECTED_COLOR`
**Checklist**:
=> fix: Adds expected text for toContainHTML checks that fail (#299)

README.md
**What**:
Docs small update.
**Why**:
I spent some time going through the docs and the issues to enable it all. Could save people some time.
=> docs: Update usage in README to make it more copy-pasty

.github/workflows/validate.yml, CONTRIBUTING.md, README.md, other/MAINTAINING.md
**What**:
Renames master to main
**Why**:
Because the name main reflects what the branch is about without also having other negative connotations.
**How**:
- https://github.com/github/renaming/
- then updating all the references to master to main (the changes in this PR)
**Checklist**:
=> chore: Rename branch master to main

src/__tests__/to-contain-html.js, src/to-contain-html.js
**What**:
resolve #347
**Why**:
Because this is worth fixing
**How**:
Added `getNormalizedHtml` function, that passes the content to the HTML parser.
This caused two changes in the test case with invalid HTML: `<span data-testid="child"></div>` becomes `<span data-testid="child"></span>`
**Checklist**:
=> fix: normalize expected value in toContainHTML

README.md, src/__tests__/helpers/test-utils.js, src/__tests__/to-have-text-content.js, src/__tests__/utils.js, src/to-have-text-content.js, src/utils.js
Fixes #306
I based it off #307 but changed a lot of things, that's why I didn't keep the initial author information.
**What, Why**: Please have a look at #306
**How**: I added a `checkNode` function in `utils` so that it can be reused elsewhere. I followed the style of the other functions and also the comment in #307 about checking that we have a window before using it.
**Checklist**:
=> feat: check for any Node in toHaveTextContent

README.md
**What**:
More explicit requirements in the documentation of `toContainHTML`.
**Why**:
https://github.com/testing-library/jest-dom/issues/362#issuecomment-832100157
**How**:
**Checklist**:
Fixes #362.
=> doc: Better documentation for toContaintHTML

README.md, src/__tests__/to-have-errormessage.js, src/matchers.js, src/to-have-errormessage.js
**What**:
feature: `.toHaveErrorMessage` matcher to check whether an invalid element has requested [error message](https://www.w3.org/TR/wai-aria/#aria-errormessage).
**Why**:
This PR is basically a replacement of the stale PR #258 which implements proposal #256. 
**How**:
Most implementation and tests are copied from the original PR with some modification to address testing issues. 
**Checklist**:
=> Add `toHaveErrorMessage` matcher

README.md
**What**:
Updates the documentation of `toBeDisabled` to better describe the conditions under which an element is considered to be disabled.
**Why**:
https://github.com/testing-library/jest-dom/issues/265#issuecomment-856300025
**Checklist**:
=> docs: Update the documentation of toBeDisabled

README.md, src/__tests__/to-have-accessible-description.js, src/__tests__/to-have-description.js, src/to-have-description.js
**What**:
Properly deprecates `toHaveDescription` in favour of `toHaveAccessibleDescription`. This PR also updates the README on other deprecation-related info (e.g. `toBeEmpty` was deprecated, but it was not reflected in the README).
While this gets reviewed and merged, I'll update the type definitions in `DefinitelyTyped`.
Pinging various reviewers, but only one is enough. Thanks in advance.
**Checklist**:
=> fix: Updates deprecated matchers info

package.json, src/__tests__/to-contain-html.js, src/__tests__/to-have-display-value.js, src/__tests__/to-have-value.js, src/to-be-in-the-document.js, src/to-contain-element.js, src/to-contain-html.js, src/utils.js
**What**: Upgrade to Jest 27
**Why**: Ensuring compatibility with breaking changes in Jest 27
**How**: Upgrading packages
**Checklist**:
=> chore: upgrade to Jest 27

src/utils.js
Hey everyone! Thanks for this incredible library 🌈 
**What**:
At Storybook we are developing an addon that will allow developers to run interaction tests directly in the browser, using testing library. We'd also love to include the matcher extenders so that developers can use the assertions from `jest-dom/extend-expect`, however importing things directly from `css` result in the following failure:
```Module not found: Error: Can't resolve 'fs'```
This is an issue that happened as well in the `testing-library/jasmine-dom` package and was addressed with the exact same fix as this PR: https://github.com/testing-library/jasmine-dom/pull/8
**Why**:
These changes would allow this library to run in the browser without breaking
**How**:
Given that the library only needs `cssParse`, there is no …
=> import parse directly from css

src/to-have-description.js
Update the deprecate error message that is thrown when using `toHaveDescription`
=> Fix wrong deprecate error message

src/to-have-class.js
**What**:
This PR aims to make `toHaveClass` error message format to be more descriptive when `exact` option is set to `true`.
**How**:
- Before:
```js
Expected the element to have EXACTLY defined classes
alone foo:
Received
:
undefined
169 |   })
170 |
> 171 |   expect(queryByTestId('no-classes')).toHaveClass('alone', 'foo', {
|                                       ^
172 |     exact: true,
173 |   })
174 |
```
- After:
```js
expect(element).toHaveClass("alone foo")
Expected the element to have EXACTLY defined classes:
alone foo
Received:
169 |   })
170 |
> 171 |   expect(queryByTestId('no-classes')).toHaveClass('alone', 'foo', {
|                                       ^
172 |     exact: true,
173 |   })
174 |
```
**Checklist**:
**Related**:
Close #397
=> fix: Improve `toHaveClass` error message format

README.md
**What**:
Small fix on README.md
**Why**:
The `.toHaveValue` example for the select verifies for `.not.toHaveValue`, but the code example has these two options selected. That means it _should_ have this value.
**How**:
I removed the `.not` part to have the test example match the code example.
**Checklist**:
=> Fix wrong toHaveValue example

README.md, src/__tests__/to-be-disabled.js, src/to-be-disabled.js
**What**:
Allow `toBeDisabled` to match against custom elements as supported by the [WHATWG spec](https://html.spec.whatwg.org/multipage/semantics-other.html#disabled-elements).
**Why**:
Rationale and example failure + reproduction repository available at https://github.com/testing-library/jest-dom/issues/367
**How**:
~This is a draft PR I opened directly from the GitHub UI. In other words, it could not get less tested than that. I'm just opening this to see if you agree with the premise. If you do, I'll add tests, docs, etc. properly.~ Done.
**Checklist**:
- Updated Type Definitions: N/A
=> fix: add custom element support to `toBeDisabled`

src/to-have-focus.js
**What**:
The output message is confusing when using `expect(element).not.toHaveFocus()`
**Why**:
To avoid confusion.
**How**:
By updating the output message when `isNot` is truthy.
**Checklist**:
=> fix(toHaveFocus): clarify message when using `.not`

package.json, rollup.config.js
**What**:
This publishes both es modules and commonjs in the bundle.  
**Why**:
Closes #437 
**How**:
I used rollup to generate the two sets of bundles.  I'm not doing any processing on either of them aside from what rollup does by default, mostly because I'm not sure what level of browser/node support this project follows.  It would be pretty straightforward to add https://www.npmjs.com/package/@rollup/plugin-babel or otherwise configure the output as needed.
**Checklist**:
I haven't updated any documentation or tests, because I wanted to see if this was at all on the right track.
=> Publish both esm and cjs

package.json, src/utils.js
**What**:
Migrate the dependency `css` to `@adobe/css` to reduce maintained dependencies.
**Why**:
CSS package is not maintained anymore and has some sub-dependencies which are deprecated.
**How**:
Change the import
**Checklist**:
=> Migrate ccs v3 to @adobe/css-tools v4

README.md, src/__tests__/to-have-accessible-errormessage.js, src/matchers.js, src/to-have-accessible-errormessage.js, src/to-have-errormessage.js
Primarily, this PR is intended to be a fix that conforms the original `toHaveErrorMessage` method more closely to the [WAI ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#aria-errormessage). This PR also renames `toHaveErrorMessage` to `toHaveAccessibleErrorMessage`.
There was also a slight change to how the assertions are exported from `matchers.js`.
Currently, there are some ways in which `toHaveErrorMessage` doesn't conform to the specifications:
- `aria-errormessage` is expected to be a single `id`, not a list of `id`s. Supplying multiple `id`s is illegal (because it would constitute an invalid singular `id`). I didn't recognize this until reading through the spec more closely.
- The cases in which an element technically "does not have an accessible error message" could be improved for …
=> Conform `toHaveErrorMessage` to Spec and Rename to `toHaveAccessibleErrorMessage`

.github/workflows/validate.yml, README.md, extend-expect.js, jest-globals.d.ts, jest-globals.js, matchers.d.ts, package.json, src/extend-expect.js, src/index.js, src/to-be-in-the-document.js, src/to-contain-element.js, src/to-contain-html.js, src/utils.js, tests/setup-env.js, tsconfig.json, types/index.d.ts, types/jest-globals.d.ts, types/jest.d.ts, types/matchers.d.ts, types/vitest.d.ts, vitest.d.ts, vitest.js
**What**:
Moves matcher types back into this package and adds support for `@jest/globals` and `vitest`, both in terms of automatically extending `expect` and augmenting the appropriate TypeScript interfaces.
There are three **breaking changes** here:
1. Drop support for node < 14
2. Removes the extend-expect script. Users should use the default import path or one of the new test platform-specific paths to automatically extend the appropriate "expect" instance. `extend-expect` was not documented in the Readme, so this change should have minimal impact.
3. Remove the `@types/` dependency. This might affect _JavaScript_ users who were relying on the automatic inclusion of the `@types/` package to get auto-complete in their editor for jest-dom assertions.
But in my local testing with the …
=> feat!: local types, supporting jest, @jest/globals, vitest

package.json, rollup.config.js, src/jest-globals.js, src/to-have-form-values.js, src/to-have-value.js, src/utils.js, src/vitest.js
**What**:
This is a re-implementation of https://github.com/testing-library/jest-dom/pull/438 and https://github.com/testing-library/jest-dom/pull/453 which upgrades the `build` command to generate both esm and cjs bundles, for each of the entry files now exposed  in 6.0 (`index`, `matchers`, `jest-global`, and `vitest`).  
Closes https://github.com/testing-library/jest-dom/pull/498
**Why**:
Closes #437 
**How**:
I replaced kcd-scripts with rollup, configured to generate esm and cjs bundles.  
I added `exports` to the `package.json` to support these multiple exports, but lied slightly in the `types` field, since we only have one type definition for both cjs and esm, when technically we should have two, one for each format.  But, since we're not actually generating these definitions from …
=> Publish ESM and CJS

package.json
**What**:
Fixes #524.
**Why**:
#519 added ESM support, but previous versions of `@adobe/css-tools` were not ESM compatible.
**How**:
Changed `package.json`
**Checklist**:
=> fix: bump @adobe/css-tools for ESM support

src/jest-globals.js
**What**:
Change import from `@jest/globals` to use direct import instead of default import.
**Why**:
Fixes #529.
`@jest/globals` does not have a default export, so in environments that do not use synthetic default import logic, either `import {expect}` or `import * as globals` is needed. I chose the former.
**Checklist**:
=> fix: proper @jest/globals import

package.json
**What**:
This PR bumps the `@adobe/css-tools` dependency to 4.3.1
**Why**:
There is an existing advisory on version `4.3.0`:
https://github.com/advisories/GHSA-hpx4-r86g-5jrg
**How**:
Updated `package.json`.
**Checklist**:
=> fix: upgrade `@adobe/css-tools` to `4.3.1` to address vulnerability

README.md
**What**:
- Updates README.md with 2 missing `<hr />`  for readability
- Between `toHaveFormValues` and `toHaveStyle`
- Between `toBeInTheDOM` and `toHaveDescription`
**Why**:
For readability
**Checklist**:
=> Add missing hr to README.md

src/__tests__/to-have-style.js, src/to-have-style.js
**What**:
support uppercase custom props in toHaveStyle
fixes #551
**Why**:
CSS custom properties are case sensitive
**How**:
don't lowercase custom property names before comparing them
**Checklist**:
--
please squash and merge
related: #148, #164
=> fix: support uppercase custom props in toHaveStyle

types/matchers.d.ts
**What**: Fix typo at `toHaveStyle` function description 🙂 
**Why**: `data-test-id` is wrong
**How**: updated to `data-testid`
=> Fix typo at toHaveStyle function description

README.md, package.json, src/__tests__/to-have-accessible-description.js
**What**:
Update `dom-accessibility-api` to `0.6.3`
https://github.com/eps1lon/dom-accessibility-api/blob/main/CHANGELOG.md
**Why**:
Fixes #487
The latest version of dom-accessibility-api supports[ `aria-description`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description#description). 
**How**:
Update the package and ran `npm run test:update`
**Checklist**:
=> Update `dom-accessibility-api` to `0.6.3`

types/matchers-standalone.d.ts
**What**:
This PR adds an export of the type `TestingLibraryMatchers` to the `"./matchers"` export.
This is a _little_ weird because the `TestingLibraryMatchers` type is not strictly relevant to the `"./matchers"` export--part of the reason #566 was submitted in the first place. `TestingLibraryMatchers` really only applies to the default `"."` export, but since the default export isn't a module (because it doesn't export anything), `"./matchers"` is probably the right place.
**Why**:
#566 introduced an unintended breaking change.
**Checklist**:
=> Export type `TestingLibraryMatchers` from "./matchers"

package.json, src/to-have-form-values.js, src/to-have-value.js, src/utils.js
**What**: 
Replace lodash logic and remove it from deps
**Why**: 
To resolve this issue -> #592 
**How**:
https://youmightnotneed.com/lodash/
**Checklist**:
=> refactor: remove lodash

src/to-have-form-values.js, src/to-have-value.js
Resolves https://github.com/testing-library/jest-dom/issues/598
=> fix: add js suffix to isEqualWith import

package.json
**What**:
Fixes #614
**Why**:
The `@babel/runtime` package is not used, but is in the dependency list. This means that it will be downloaded on every installation. Its size is about 240kb, which isn't much, but given the 11 million weekly downloads, it will be a noticeable change in the JS ecosystem.
**How**:
Simply removing the package from the dependency list.
**Checklist**:
=> chore: remove unused @babel/runtime dependency

README.md, src/__tests__/to-have-value.js, src/utils.js
Resolves #478
**What**:
Change `.toHaveValue()` to support `aria-valuenow`
**Why**:
**How**:
**Checklist**:
=> feat(toHaveValue): Asserting aria-valuenow

README.md
**What**:
Readme was missing info how to update tsconfig for vitest users so extended matchers are not workin in runtime only but also on type checks in devs IDE
**Why**:
To help devs using typescript and vitest to have typed matchers
**How**:
After finding solution I edited readme
**Checklist**:
=> Readme - how to update tsconfig for vitest matchers extension

src/to-have-selection.js
Lodash import needs to have the `.js` extension.
Fixes https://github.com/testing-library/jest-dom/issues/641
=> fix: fix lodash import in to-have-selection.js

types/vitest.d.ts
**What**:
Replaces the dynamic lookup of the return type of `expect.stringContaining` with the underlying type
**Why**:
This resolves the TypeScript errors introduced by #612, as described in #629
**How**:
By replacing the use of `expect.stringContaining` with a concrete type - I don't actually know why `ReturnType` was being used in the first place given that `expect.stringContaining` has a return type of `any` and I don't really see that changing anytime in the future.
**Checklist**:
Resolves #632
Resolves #629
=> fix: remove recursive type reference in vitest types

types/vitest.d.ts
**What**:
https://github.com/testing-library/jest-dom/issues/645
Fix a vitest typing issue when using global mode
**Why**:
If there is no import of "vitest" in the whole project (for example, vitest is in globalMode), the type merging might not work.
**How**:
By adding an import of "vitest" when extending the matcher type
reference: https://vitest.dev/guide/extending-matchers.html
**Checklist**:
=> fix: add vitest import when extending vitest matchers

package.json, src/to-have-style.js
**What**:
This PR replaces `chalk` with [`picocolors`](https://github.com/alexeyraspopov/picocolors).
**Why**:
Picocolors is smaller and faster.
For a reference see https://github.com/es-tooling/ecosystem-cleanup/issues/132.
**How**:
Uninstalled `chalked`, and installed `picocolors`.
Renamed the import
**Checklist**:
This is similar to https://github.com/testing-library/dom-testing-library/pull/1341
=> perf: replace chalk with picocolors
