README.md
I really need to remove that from my template :sweat_smile:
=> docs: remove sponsor

README.md
**What**: documentation to extend jest.Matchers interface in typescript
**Why**: proposed type-casting is ugly
**How**: edited README
**Checklist**:
=> docs: more robust typescript instructions

extend-expect.d.ts
**What**:
- Convert matcher function definitions to instance methods (rather than function properties)
- Allow `RegExp` in `toHaveTextContent` typings 
**Why**:
- Jest's typings (on DefinitelyTyped) use instance methods for matchers &mdash; this difference is mostly cosmetic, but TypeScript does treat methods slightly differently from function properties with respect to generics when `strictFunctionTypes` is enabled
- `toHaveTextContent` implementation allows a RegExp to be passed instead of a string
Typings before:
Typings after:
**How**:
- Updated extend-expect.d.ts
**Checklist**:
=> TypeScript: Convert matchers to instance methods

.github/PULL_REQUEST_TEMPLATE.md
- Moved the questions to come after the titles
- Added updated type definitions so they stay in sync
**What**:
Updated pull request template to make it easier to read and to add type definition updates
**Why**:
To improve developer experience and helping types to stay in sync. 
**How**:
Updated the pull request template
**Checklist**:
=> docs: Adjusted pull request template

README.md, extend-expect.d.ts
**What**:
Widen types to include `SVGElement` where appropriate (per https://github.com/gnapse/jest-dom/pull/36#discussion_r201725050).
**Why**:
More accurately reflects the runtime behaviour.
**How**:
Updated type definitions and readme.
**Checklist**:
* [] Added myself to contributors table  N/A
=> Typings: Allow SVGElement in toContainElement and toBeInTheDOM

jest.config.js
**What**:
Implemented fix from @jgoz to failing TI builds. See the following for more details:
https://github.com/gnapse/jest-dom/pull/47#issuecomment-409612156
**Why**:
The Travis builds are currently failing.
**How**:
Implemented fix from @jgoz and added a testURL into the jest.config
**Checklist**:
=> fix: Added testURL in jest.config

README.md
**What**:
Updated README matcher examples to be more consistent
Updated README matcher intro with note about `jest-dom` varied usage
Organized README matcher examples in alphabetical order
**Why**:
To improve and create a consistent experience with matcher examples 
**How**:
Updated the README examples to be similar to the discussion in  #50 
**Checklist**:
Closes #50
=> #50: Reorganized, updated, and prefaced custom matcher examples

.all-contributorsrc, README.md
**What**:
It closes #73.
**Checklist**:
=> Improve toHaveTextContent documentation

package.json
**What**:
Bump the dependencies from Jest's monorepo to their latest
**Why**:
To dedupe better and use the latest and greatest
**How**:
`yarn upgrade-interactive`
**Checklist**:
=> fix: bump new jest dependencies

extend-expect.d.ts
**What**:
Added missing type declaration
**Why**:
Type declaration was missing
**Checklist**:
=> Add type declaration for toBeEnabled

README.md
**What**:
Tiny typo (missing bracket) in toHaveFocus() example
**Why**:
N/A
**How**:
N/A
**Checklist**:
=> Fix: missing closing bracket in toHaveFocus() example

README.md
**What**:
Update link to Jest documentation with the new method to configure a setup file.
**Why**:
`setupTestFrameworkScriptFile` is deprecated in favor of `setupFilesAfterEnv`.
**How**:
N/A
**Checklist**:
=> docs: update deprecated method of jest

README.md
=> docs: fix owl url

README.md
**What**:
Just fixing a couple of broken links in the readme
**Why**:
Noticed they were broken
**How**:
This seems unnecessary to answer for this PR
**Checklist**:
=> Fix some links in the Readme

README.md
**What**:
This fixes a typo as toHaveFormValue is not exported by this library, it should be toHaveFormValues.
**Why**:
Importing toHaveFormValue causes an error, which could be confusing to new users.
**How**:
Replace toHaveFormValue with toHaveFormValues.
**Checklist**:
=> Replace toHaveFormValue with toHaveFormValues

README.md
**What**:
add link to lint plugin
**Why**:
to increase visibility of the lint plugin. 😎 
**How**:
**Checklist**:
=> docs: added link to lint plugin

package.json
Fixes #123
Closes #160
Fixes #185
**What**:
Add typings as a dependency to the project.
**Why**:
#123.
**How**:
Added types to `package.json`.
**Checklist**:
=> Add @types/testing-library__jest-dom dependency

README.md
**What**:
Just a quick typo fix in the readme.
**Why**:
Not necessary, but just nice to keep the text free of typos.
**How**:
Quick update to the typos.
**Checklist**:
=> docs(readme): Fix typo 

README.md
**What**: Made updates for installation using yarn.
**Why**: For users/developers who are using yarn as the package manager.
**How**: By adding the yarn add bash script.
**Checklist**:
=> docs(readme): Add yarn install command

src/__tests__/to-have-class.js
Removed a duplicate assertion on the tests for **toHaveClass**.
**Checklist**:
- [N/A] Documentation
- [N/A] Updated Type Definitions
=> fix: removed duplicate assertion

package.json, src/to-be-checked.js
**What**:
This updates the version of `aria-query` to 5.0.0.  
**Why**:
Closes #413.
**How**:
This is a breaking change in that Map and Set are no longer used.  But, the `roles` object that is returned has methods on it, including `.get()`, which is used in `roleSupportsChecked`.
The only update I made to the code is to remove the `Array.from()` call, since `roles.keys()` already returns an array now.
**Checklist**:
=> Update aria-query to 5.0.0

.github/ISSUE_TEMPLATE/Bug_Report.md
**What**:
Added jest/vitest version to bug report template
**Why**:
e.g. #524 was missing this essential env information for the issue to be reproduced.
**How**:
**Checklist**:
=> chore: add jest/vitest version to bug report template

package.json
**What**:
This PR bumps @adobe/css-tools to version 4.3.2
**Why**:
There is an existing advisory on version 4.3.1
https://github.com/advisories/GHSA-prr3-c3m5-p7q2
**How**:
**Checklist**:
=> vulnerability fix: upgrade @adobe/css-tools to v4.3.2

.github/workflows/validate.yml
This PR unblocks the CI by upgrading the action version and adding a token.
=> fix(infra): codecoverage token addition

types/matchers-standalone.d.ts
see https://github.com/testing-library/jest-dom/issues/605
**What**:
Typescript definition file
**Why**:
Duplicate identifier error.
**How**:
Correcting the definition.
**Checklist**:
Using suggested solution from issue poster @aliu-vmware
=> fix: Type definition of `toHaveClass`

package.json
**What**:
Drop peerDependencies from package.json
**Why**:
See https://github.com/testing-library/jest-dom/issues/608 for the complete motivation, and discussion
Closes #608 
**How**:
Editing package.json
**Checklist**:
=> chore: Drop peerDependencies from package.json

README.md
**What**:
Fix the invalid GitHub Actions badge URL. Please read the details at https://github.com/badges/shields/issues/8671.
Before:
After:
**Why**:
Because the old image URL shows the error image now.
**How**:
Replace the old badge URL with the new format by following the instruction in the above issue.
**Checklist**:
=> docs: adopt the new build-badge URL

.github/dependabot.yml
This will create automatic PRs to update both dependencies + actions used in workflows, so we won't need manual PRs like #414 anymore
=> chore: add `dependebot.yml`
